package main

import (
	"flag"
	"fmt"
	"math/rand"
	"os"
	"sync"
	"time"

	"github.com/zyy17/logbench/pkg/dataset"
	"github.com/zyy17/logbench/pkg/generator"
	"github.com/zyy17/logbench/pkg/ingester"
)

type Options struct {
	BatchSize  int
	Ops        int
	Endpoint   string
	Pipeline   string
	AppNum     int
	ClusterNum int
	LogSize    int64
}

var distributionConfig = []string{
	"20%:200bytes-1kb",
	"76%:1kb-2kb",
	"3.5%:2kb-100kb",
	"0.4%:200kb-1mb",
	"0.1%:1mb-5mb",
}

func main() {
	batchSize := flag.Int("batch-size", 0, "number of logs to ingest")
	ops := flag.Int("ops", 0, "number of operations to perform")
	endpoint := flag.String("endpoint", "http://localhost:4000", "endpoint to ingest logs to")
	pipeline := flag.String("pipeline", "greptime_identity", "pipeline name to ingest logs to")
	appNum := flag.Int("app-num", 50, "number of apps to generate logs")
	clusterNum := flag.Int("cluster-num", 40, "number of clusters to generate logs")
	logSize := flag.Int("log-size", 0, "use fixed log size to generate logs(bytes) or it will be generated by builtin probability distribution")
	flag.Parse()

	if *batchSize == 0 {
		fmt.Println("batch-size is required")
		os.Exit(1)
	}

	if *ops == 0 {
		fmt.Println("ops is required")
		os.Exit(1)
	}

	if *ops < *batchSize {
		fmt.Println("ops must be greater than batch-size")
		os.Exit(1)
	}

	options := &Options{
		BatchSize:  *batchSize,
		Ops:        *ops,
		Endpoint:   *endpoint,
		Pipeline:   *pipeline,
		AppNum:     *appNum,
		ClusterNum: *clusterNum,
		LogSize:    int64(*logSize),
	}

	generator, err := generator.NewGenerator(distributionConfig, options.LogSize, dataset.DatasetType(dataset.Zookeeper2kDatasetType))
	if err != nil {
		panic(err)
	}

	ingester, err := ingester.NewIngester(options.Endpoint, options.Pipeline, true)
	if err != nil {
		panic(err)
	}

	// Calculate the number of concurrent tasks
	concurrencyNum := options.Ops / options.BatchSize

	fmt.Printf("Starting benchmark with options: %+v\n", options)
	for {
		doBenchmark(options, generator, ingester, concurrencyNum)
	}
}

func doBenchmark(opts *Options, generator *generator.Generator, ingester *ingester.Ingester, concurrencyNum int) {
	var wg sync.WaitGroup
	start := time.Now()

	for i := 0; i < concurrencyNum; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			clusterIndex := rand.Intn(opts.ClusterNum) + 1
			appIndex := rand.Intn(opts.AppNum) + 1
			cluster := fmt.Sprintf("cluster%d", clusterIndex)
			app := fmt.Sprintf("app%d", appIndex)

			data, err := generator.Generate(cluster, app, opts.BatchSize, time.Now().Format(time.RFC3339), 0)
			if err != nil {
				fmt.Printf("generate logs failed: %v\n", err)
			}

			if err := ingester.Ingest(cluster, app, data); err != nil {
				fmt.Printf("ingest logs failed: %v\n", err)
			}
		}()
	}
	wg.Wait()
	elapsed := time.Since(start)

	// Sleep if the elapsed time is less than 1 second.
	if elapsed < time.Second*1 {
		time.Sleep(time.Second*1 - elapsed)
	}
}
